version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/lost_and_found
    depends_on:
      - mongo
    volumes:
      - uploads_data:/app/BACKEND/uploads
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
  uploads_data: 