services:
  - type: web
    name: lost-and-found-app
    env: docker
    repo: https://github.com/your-username/your-repo-name.git
    dockerfilePath: ./Dockerfile.dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    disk:
      name: uploads
      mountPath: /app/BACKEND/uploads
      sizeGB: 1 